### ISSUE TITLE
Compiler warnings with gcc 8.2.0

### ISSUE THREAD

**Issue by phmarek** [guicho271828/trivial-signal#11]
```
trivial-signal-20151031-git/src/grovel__grovel.c:564:16: warning: extra tokens at end of #ifdef directive                    
 #ifdef SIGRTMIN+1
                ^
```
These are repeated for every of these `#ifdef` lines; perhaps that's something that should be fixed in CFFI, though.

**Comment by guicho271828** [comment]
I think I misunderstood that there would be a C macro named "SIGRTMIN+1", but if I think just more bit it was obvious that there is just one SIGRTMIN macro and SIGRTMIN+1 is nothing more than an addtion. I will just remove those extra symbols.
