### ISSUE TITLE
signal-handler-bind doesn't work

### ISSUE THREAD

**Issue by mrkkrp** [guicho271828/trivial-signal#4]
Here is simplified version of what I've got:

```
(define-condition got-sigint (serious-condition)
  ()
  (:documentation "Auxiliary condition to handle SIGINT."))

(defmacro with-exit-on-sigint (&body body)
  "Immediately exit BODY if SIGINT is sent."
  `(handler-case
       (signal-handler-bind ((:int
                              (lambda (c)
                                (declare (ignore c))
                                (error 'got-sigint))))
         ,@body)
     (got-sigint (condition)
       (declare (ignore condition))
       some stuff here)))
```

When I press <kbd>C-c</kbd> in terminal, I get this:

```
^CSignal 2 masked
fatal error encountered in SBCL pid 14202(tid 140737353963264):
some deferrable signals blocked, some unblocked


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```

My macro works fine when I just catch exception `sb-sys:interactive-interrupt`, but it's implementation dependent solution. Why this version doesn't work?

P.S. You need to write normal documentation string for `signal-handler-bind` (since it's your API), it should describe structure of `bindings` argument, etc.

**Comment by guicho271828** [comment]
=sb-sys:interactive-interrupt= is exactly what is related to the failure, although I have not investigated the mechanics. It steals the signal and prevents =signal-handler-bind= to handle it.  See https://github.com/guicho271828/trivial-signal#threading-policy , trivial-signal is not capable of capturing some signals, which is implementation dependent.

**Comment by guicho271828** [comment]
I agree regarding the documentation. thanks. I will work on this.

**Comment by guicho271828** [comment]
If you read the source, you would notice that there is a plenty room for improvements e.g.

+ use cffi-grovel to obtain the right number for each signal on different OSes
+ use sigaction(2) instead of signal(2)
+ adding atexit

**Comment by mrkkrp** [comment]
OK, I will use [macro that catches SBCL-specific exception](https://github.com/mrkkrp/shtookovina/blob/master/src/session.lisp#L256-L266) for now. Let me know if something changes with `trivial-signal`.

**Comment by akacase** [comment]
sbcl 1.3.9 has fixed this issue for me.

**Comment by vindarel** [comment]
@akacase with sbcl 1.3.19 I have the same error message and the ldb prompt :/ maybe can you post an example that's working for you ?

**Comment by guicho271828** [comment]
@vindarel it is also possible that this is OS-dependent.
