### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by spacebat** [guicho271828/trivial-signal#8]
On OSX El Capitan (10.11.6) and SBCL 1.3.10 it appears TRIVIAL-SIGNAL does not work. If I run the following:

```common-lisp
(ql:quickload :trivial-signal)
(use-package :trivial-signal)

(defun exit-on-signal (signo)
  (format *error-output* "~&received ~A~%" (signal-name signo))
  (finish-output *error-output*))

(setf (signal-handler :term) #'exit-on-signal) ;; :term can also be :sigterm or 15

(loop
  do (format *error-output* "Sleeping 5 seconds~%")
     (finish-output *error-output*)
     (sleep 5))
```

Like this:

$ (sbcl --load ~/signal-handler.lisp >/dev/null)& sleep 3; pkill -TERM sbcl; echo $?; pgrep sbcl
[1] 64551
Sleeping 5 seconds
0
[1]+  Done                    ( sbcl --load ~/signal-handler.lisp > /dev/null )

You can see that pkill does send a signal to sbcl, no received signal is reported, and that afterward sbcl has exited.

**Comment by guicho271828** [comment]
https://github.com/guicho271828/trivial-signal#some-signals-may-not-work-right

**Comment by guicho271828** [comment]
sbcl on OSX may be using a different signal handling internal than sbcl on Linux. its all up to implementation details.

**Comment by svetlyak40wt** [comment]
Checked again with SBCL 1.4.1 and CCL 1.11-r16635 – signals `sigint` and `sigterm` aren't work.

**Comment by svetlyak40wt** [comment]
Actually, I've checked how global handlers work. And they doesn't. But when I tried this code:

```
#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#
(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp (ql:quickload '(trivial-signal) :silent t))

(defpackage :ros.script.test.3721012612
  (:use :cl :trivial-signal))
(in-package :ros.script.test.3721012612)

(defun main (&rest argv)
  (declare (ignorable argv))
  (format t "Going to sleep~%")
  (signal-handler-bind ((:term (lambda (signo)
                                 (format t "TERMINATING~%")
                                 (uiop:quit 1)))
                        (:int (lambda (signo)
                                 (format t "CANCELLING~%")
                                 (uiop:quit 1))))
    (sleep 30))
  (format t "Done~%"))
```

it is able to handle Ctrl-C, but produces weird output in CCL (presumable, added for debugging):

```
Going to sleep
^C-------- handler invoked in thread: listener -------
hierarchy: (((2 #<Compiled-function (INTERNAL MAIN) (Non-Global)  #x3020015B60EF>) (15 #<Compiled-function (INTERNAL MAIN) (Non-Global)  #x3020015B695F>)))CANCELLING
```

And crashes in SBCL:

```
Going to sleep
^CSignal 2 masked
fatal error encountered in SBCL pid 650(tid 0x7fff76b82000):
some deferrable signals blocked, some unblocked
```

This behaviour is the same for compiled version of the script.

**Comment by svetlyak40wt** [comment]
Do this issue was closed because it was fixed?

**Comment by guicho271828** [comment]
It won't be fixed unless we patch sbcl itself. I don't want that. this lib doesn't handle the signals that conflict with the implementation internals
